### ISSUE TITLE
[Question] How to convert HashSet.RemoveWhere() to concurrent version?

### ISSUE THREAD

**Issue by JeReT** [i3arnon/ConcurrentHashSet#20]
I need to replace a hashset with a concurrent hashset.
I call "RemoveWhere" on the prior HashSet. This is not present in ConcurrentHashSet<T> and I try to wrap my head around of how to implement this.

Right now, my solution is keeping the non-concurrent-hashset and put every operation with it inside a lock statement. But I wonder if there is a more elegant way with the ConcurrentHashSet (or if it would be possible to implement "RemoveWhere" there).

**Comment by JeReT** [comment]
Hmm, I wonder if this would be thread-safe:

```csharp
if (myHashset.Any(MyPredicate))
{
    var itemsToRemove = myHashset.Where(MyPredicate).ToArray();

    foreach (var item in itemsToRemove)
    {
        myHashset.TryRemove(item);
    }
}
```

**Comment by i3arnon** [comment]
`RemoveWhere` is an O(n) operation.
You can do it on the existing `ConcurrentHashSet` but you can't guarantee all the items matching the predicate are removed after the operation completes (as they can be added meanwhile).
In order to provide that gurantee you would need to lock the instance througout the operation and then there's no point in using this instead of a `HashSet` with a lock.

If you don't need that guarantee then there you go:

```
public static class ConcurrentHashSetExtensions
{
    public static int RemoveWhere<T>(this ConcurrentHashSet<T> concurrentHashSet, Func<T, bool> match)
    {
        var removed = 0;
        foreach (var element in concurrentHashSet)
        {
            if (match(element))
            {
                concurrentHashSet.TryRemove(element);
                removed++;
            }
        }

        return removed;
    }
}
```
