### ISSUE TITLE
ConcurrentHashSet does not accept null comparer

### ISSUE THREAD

**Issue by hrumhurum** [i3arnon/ConcurrentHashSet#6]
ConcurrentHashSet does not accept null comparer in constructor while HashSet has no problem with it whatsoever.

The line:

`var hashSet = new ConcurrentHashSet<string>((IEqualityComparer<string>)null);`

throws ArgumentNullException while line:

`var hashSet = new HashSet<string>((IEqualityComparer<string>)null);`

works fine.

My quick suggestion is to remove the line from ConcurrentHashSet constructor:

 `if (comparer == null) throw new ArgumentNullException(nameof(comparer));`

and change the line

` _comparer = comparer;`

to

` _comparer = comparer ?? EqualityComparer<T>.Default;`

**Comment by i3arnon** [comment]
`ConcurrentDictionary` throws on `null` as well even though `Dictionary` does not.

I don't know if that's intentional but maybe the .NET devs decided throwing on null is safer when they added the concurrent collections but couldn't break the `Dictionary`'s old implementation.

I'm not sure allowing `null` is better. Most cases of sending `null` would be unintentional and the others would be relying on internal implementation details.

**Comment by hrumhurum** [comment]
You are right. ConcurrentHashSet should follow ConcurrentDictionary semantics in this regard.

P.S. Thank you for the great effort on making this project real. It saved my day. Wonder why Microsoft did not include this as a part of .NET Framework.

Cheers

**Comment by jnm2** [comment]
I'm not so sure about this. https://github.com/dotnet/corefx/issues/18432

**Comment by i3arnon** [comment]
@jnm2 if this ends up changing in `ConcurrentDictionary`, I will definitely change `ConcurrentHashSet` as well.

**Comment by i3arnon** [comment]
Changed in https://github.com/i3arnon/ConcurrentHashSet/commit/b9ce11c825ccd766270a307ce0923325a55bd112.
Thanks @hrumhurum & @jnm2 for the initiative.
