### ISSUE TITLE
Should Add be renamed to TryAdd to be consistent with ConcurrentDictionary?

### ISSUE THREAD

**Issue by NeoXtreem** [i3arnon/ConcurrentHashSet#8]
This would also complement the existing TryRemove method.

**Comment by i3arnon** [comment]
The thing is: In `ConcurrentDictionary` `TryAdd` returns `false` when it fails to add the value because there's another value indexed by the same key. In `ConcurrentHashSet` there's no value, just the key. If the key exists adding the same key can't "really" fail, the state is the same as if `TryAdd` succeeded. There's no `Try`, only do.

**Comment by jnm2** [comment]
Also, corefx has `TryAdd` for Dictionary and not for `HashSet` so @i3arnon is consistent in this regard.
